### PR TITLE
Upgrade to Stylelint 16 and migrate to ESM

### PR DESCRIPTION
**Pull request by connor-baer**
[Stylelint 16](https://github.com/stylelint/stylelint/releases/tag/16.0.0) was recently released. It brings support for ESM plugins and raises the minimum Node.js version to 18.12.

This pull request upgrades the project according to the [migration guide](https://stylelint.io/migration-guide/to-16/#removed-support-for-nodejs-less-than-18120).

### CODE REVIEW

**Comment by connor-baer** [comment]
I'm going to rebase the branch to resolve the conflicts.

**Comment by stormwarning** [comment]
@connor-baer This might need another rebase in a bit; just wanted to get a couple quick additions in before the breaking change 🙏

**Comment by connor-baer** [comment]
Hey @stormwarning, are you planning any other changes before the breaking change? Anything I can help with? 

I'd love to get this pull request released so that I can upgrade my projects to Stylelint 16 🙏🏻

**Comment by stormwarning** [comment]
Thanks for the nudge @connor-baer 😅 I should have this update out later today.

**Pull request merged**
