### PR TITLE
Update stylelint-order version to enable autofix

### PR DESCRIPTION
**Pull request by yakhinvadim**
Hi! Thank you for your plugin. I wanted to use an updated version to be able to autofix order with "stylelint --fix", but it's supported only in version 0.5.0: https://github.com/hudochenkov/stylelint-order/releases/tag/0.5.0, so here's a PR :)

### CODE REVIEW

**Comment by stormwarning** [comment]
Thanks!

**Comment by yakhinvadim** [comment]
@stormwarning Sorry for bothering :) Are you going to publish a new version to npm any time soon? Or are you going to add something else and publish after that?

**Comment by stormwarning** [comment]
Oh yeah, I guess that would be necessary wouldn't it... 🙄  I'll see if I had anything underway locally and I should push out a new version in a little bit here.

**Comment by stormwarning** [comment]
@yakhinvadim new version should be available from npm now!

**Comment by yakhinvadim** [comment]
Great, thanks!

**Pull request merged**
