### PR TITLE
🎁 Add `place-content` and `place-self` properties

### PR DESCRIPTION
**Pull request by chalkygames123**
Following up #193. See:

- https://developer.mozilla.org/en-US/docs/Web/CSS/place-content
- https://developer.mozilla.org/en-US/docs/Web/CSS/place-self

### CODE REVIEW

**Comment by SharakPL** [comment]
Shouldn't it be before `place-items` like in `align-` set?

**Comment by chalkygames123** [comment]
Ah yeah, good catch. Thank you.

**Comment by stormwarning** [comment]
Thanks for the PR (apologies for the delay reviewing)!

**Comment by stormwarning** [comment]
Would you mind adding a changeset by running `npm run changeset`? It should be marked as a `minor` release

**Comment by chalkygames123** [comment]
No problem :)

Alright, I did it!

**Pull request merged**
